obj-$(CONFIG_KEYPAD_CYPRESS_TOUCH_SAMSUNG)	+= cypress-touchkey.o
obj-$(CONFIG_KEYPAD_CYPRESS_TOUCH_SAMSUNG)	+= issp_driver_routines.o
obj-$(CONFIG_KEYPAD_CYPRESS_TOUCH_SAMSUNG)	+= issp_main.o
obj-$(CONFIG_KEYPAD_CYPRESS_TOUCH_SAMSUNG)	+= issp_routines.o
